import Head from 'next/head';
import styled from 'styled-components';
import NavigationBar from '../components/NavigationBar';

const Background = styled.div`
  width: 100%;
  height: 100%;
`;

export default function Crew() {
  return (
    <Background>
      <Head>
        <title>크루</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationBar />
    </Background>
  )
}
