import Head from 'next/head';
import styled from 'styled-components';
import LayoutWithNav from '../components/LayoutWithNav';

const Background = styled.div`
  width: 100%;
  height: 100%;
`;

export default function Crew() {
  return (
    <Background>
      <Head>
        <title>홈</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutWithNav>
        <p>Crew</p>
        <p>Test</p>
      </LayoutWithNav>
    </Background>
  )
}
