import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useRecoilState } from 'recoil';
import styled from 'styled-components';
import { useMediaQuery } from 'react-responsive';

import LayoutWithNav from '../components/LayoutWithNav';
import { ProfilePic } from '../components/ProfilePic';

import { characterState } from '../features/atoms';

import * as Text from '../styles/TextStyles';

const TitleWrap = styled.div`
  display: flex;
  justify-content: space-between;

  width: 100%;
`;

type TitleProps = {
  scrolled: boolean;
}

function Title({ scrolled }: TitleProps) {
  const [character, setCharacter] = useRecoilState(characterState);

  const isMobile = useMediaQuery({
    query: "(min-width: 320px) and (max-width: 519px)"
  });

  if (character.isLogined) {
    return (
      <TitleWrap>
        <span>
          <Text.Subtitle2B>
            {character.characterName}
          </Text.Subtitle2B>
          <Text.Subtitle2R>
            의<br />피드
          </Text.Subtitle2R>
        </span>
        <ProfilePic
          size={scrolled && isMobile ? 28 : 40}
          image={character.image}
        />
      </TitleWrap>
      )
  }
  else {
    return (
      <TitleWrap>
        <span>
          <Text.Subtitle2R>
            눈길이 가는
          </Text.Subtitle2R>
          <Text.Subtitle2B>
            <br />피드
          </Text.Subtitle2B>
        </span>
        <ProfilePic
          size={scrolled && isMobile ? 28 : 40}
        />
      </TitleWrap>
    )
  }
}

const Background = styled.div`
  width: 100%;
  height: 100%;
`;

export default function Home() {
  const [character, setCharacter] = useRecoilState(characterState);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    setCharacter({
      isLogined: true,
      characterName: '단호좌현지',
      caption: '나는 나보다 약한 자의 말은 듣지 않는다',
      image: 'https://images.unsplash.com/photo-1626688226927-33257a21236f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1268&q=80',
    });
  }, [setCharacter]);

  return (
    <Background>
      <Head>
        <title>홈</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutWithNav
        topElement={<Title scrolled={scrolled} />}
        setScrolled={setScrolled}
      >
        <p>b</p>
        <p>b</p>
        <p>b</p>
        <p>b</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>b</p>
        <p>b</p>
        <p>b</p>
      </LayoutWithNav>
    </Background>
  )
}