import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';
import { atom, useRecoilState } from 'recoil';

const testAtom = atom({
  key: 'test',
  default: '',
});

const Example = styled.div`
  background-color: #000000;
  width: 500px;
  height: 500px;
`;

const Text = styled.p`
  color: #ffffff;
`;

export default function Home() {
  const [test, setTest] = useRecoilState(testAtom);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Example onClick={() => setTest('Test Text!')}>
        <Text>{test}</Text>
      </Example>
    </div>
  )
}
