import { useState } from 'react';
import Head from 'next/head';
import styled from 'styled-components';

import LayoutWithNav from '../components/LayoutWithNav';
import ProfileMini from '../components/ProfileMini';
import SearchInput from '../components/SearchInput';

const Background = styled.div`
  width: 100%;
  height: 100%;
`;

export default function Search() {
  const [scrolled, setScrolled] = useState(false);

  return (
    <Background>
      <Head>
        <title>홈</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutWithNav
        setScrolled={setScrolled}
        topElement={<SearchInput scrolled={scrolled} />}
      >
        <ProfileMini varient="vertical" />
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
        <p>a</p>
      </LayoutWithNav>
    </Background>
  )
}